name: mapalus
description: Platform to support local community to hopefully be able to thrive

publish_to: 'none'

version: 1.12.0+34

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  mapalus_flutter_commons:
    path: ../mapalus_flutter_commons
#    git: "https://github.com/meimodev/mapalus_flutter_commons.git"


  firebase_core: ^2.25.4
  flutter_native_splash: ^2.2.16
  get: ^4.6.6

dev_dependencies:
  flutter_launcher_icons: '^0.9.2'
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/icon-1024x1024.png'

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/vectors/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

flutter_native_splash:
  color: "#2B2E33"
  image: assets/images/splash-mobile-primary-900x900.png
  
  