name: mapalus
description: Platform to support local community to hopefully be able to thrive

publish_to: 'none'

version: 1.1.11+12

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.5.3
  flutter_svg: ^1.1.0
  cupertino_icons: ^1.0.5
  flutter_rating_bar: ^4.0.1
  badges: ^2.0.3
  carousel_slider: ^4.1.1
  firebase_core: ^1.18.0
  cloud_firestore: ^3.1.18
  get: ^4.6.5
  intl: ^0.17.0
  jiffy: ^5.0.0
  firebase_auth: ^3.3.20
  hive: ^2.2.2
  hive_flutter: ^1.1.0
  google_maps_flutter: ^2.1.8
  url_launcher: ^6.1.4
  firebase_messaging: ^11.4.2
  flutter_local_notifications: ^9.6.1
  transparent_image: ^2.0.0
  package_info_plus: ^1.4.2
  dio: ^4.0.6
  flutter_keyboard_visibility: ^5.3.0
  firebase_app_check: ^0.0.6+14
  firebase_crashlytics: ^2.8.2

dev_dependencies:
  flutter_launcher_icons: '^0.9.2'
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/icons/icon-1024x1024.png'

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/vectors/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages