// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChe_02W038hgDONB_56zl_PO9WI58tH6w',
    appId: '1:342086903599:android:264d40408aefdb0afc63da',
    messagingSenderId: '342086903599',
    projectId: 'mapalus-a26af',
    storageBucket: 'mapalus-a26af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqyObzq2VZHOZ1fNPM5eNO6CERvYggt-s',
    appId: '1:342086903599:ios:a24d04e7d4c6af5dfc63da',
    messagingSenderId: '342086903599',
    projectId: 'mapalus-a26af',
    storageBucket: 'mapalus-a26af.appspot.com',
    androidClientId: '342086903599-5d7ht8nn9vn6vgve24g9i0uvbnivf0l1.apps.googleusercontent.com',
    iosClientId: '342086903599-slsvrmghsnosst242ekdg5mprbvrlhkr.apps.googleusercontent.com',
    iosBundleId: 'com.meimodev.mapalus',
  );

}