// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChe_02W038hgDONB_56zl_PO9WI58tH6w',
    appId: '1:342086903599:android:3d6983ff8f870622fc63da',
    messagingSenderId: '342086903599',
    projectId: 'mapalus-a26af',
    storageBucket: 'mapalus-a26af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqyObzq2VZHOZ1fNPM5eNO6CERvYggt-s',
    appId: '1:342086903599:ios:a24d04e7d4c6af5dfc63da',
    messagingSenderId: '342086903599',
    projectId: 'mapalus-a26af',
    storageBucket: 'mapalus-a26af.appspot.com',
    iosClientId: '342086903599-v0u3435mshr1pr8aas21prgbuk84i78t.apps.googleusercontent.com',
    iosBundleId: 'com.meimodev.mapalus',
  );
}
